### PR TITLE
Full Day events and import in google calendar

### PR DESCRIPTION
**Pull request by francescolovecchio**

### CODE REVIEW

**Comment by francescolovecchio** [comment]
this resolve https://github.com/davaxi/VCalendar/issues/3

**Comment by davaxi** [comment]
Can you apply this diff on your branch ?

[diff.txt](https://github.com/davaxi/VCalendar/files/1895013/diff.txt)

**Comment by francescolovecchio** [comment]
Hi, ok but not this
-                $this->getDateFormat(strtotime('+1 day', $this->endDateTime))
+                $this->getDateFormat($this->endDateTime)

If you want create an event from 25/04 to 26/04. You must write in the file 25/04 -> 27/04

And this
-        return implode("\r\n", $result);
+        return implode("\n", $result);
Because the standard want this type of EOF

**Comment by davaxi** [comment]
Ok. I test this week, i fix and complet unit tests and i merge. Thank :)

**Pull request merged**
